// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("XrmContext")>]
[<assembly: AssemblyProductAttribute("XrmContext")>]
[<assembly: AssemblyDescriptionAttribute("Tool to generate early-bound .NET classes and enumerations for MS Dynamics 365/CRM server-side coding.")>]
[<assembly: AssemblyCompanyAttribute("Delegate A/S")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Delegate A/S 2017")>]
[<assembly: AssemblyVersionAttribute("2.0.1")>]
[<assembly: AssemblyFileVersionAttribute("2.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "XrmContext"
    let [<Literal>] AssemblyProduct = "XrmContext"
    let [<Literal>] AssemblyDescription = "Tool to generate early-bound .NET classes and enumerations for MS Dynamics 365/CRM server-side coding."
    let [<Literal>] AssemblyCompany = "Delegate A/S"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Delegate A/S 2017"
    let [<Literal>] AssemblyVersion = "2.0.1"
    let [<Literal>] AssemblyFileVersion = "2.0.1"
