// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("src/XrmContext")>]
[<assembly: AssemblyProductAttribute("src/XrmContext")>]
[<assembly: AssemblyDescriptionAttribute("Tool to generate early-bound .NET classes and enumerations for MS Dynamics 365/CRM server-side coding.")>]
[<assembly: AssemblyCompanyAttribute("Delegate A/S")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Delegate A/S 2017")>]
[<assembly: AssemblyVersionAttribute("1.8.0")>]
[<assembly: AssemblyFileVersionAttribute("1.8.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "src/XrmContext"
    let [<Literal>] AssemblyProduct = "src/XrmContext"
    let [<Literal>] AssemblyDescription = "Tool to generate early-bound .NET classes and enumerations for MS Dynamics 365/CRM server-side coding."
    let [<Literal>] AssemblyCompany = "Delegate A/S"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Delegate A/S 2017"
    let [<Literal>] AssemblyVersion = "1.8.0"
    let [<Literal>] AssemblyFileVersion = "1.8.0"
